version: "3.8"
services:
  server:
    image: ilmo-server
    container_name: ilmo_server
    entrypoint: yarn server start
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

  worker:
    image: ilmo-worker
    container_name: ilmo_worker
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
      - server

  redis:
    image: redis:6-alpine
    container_name: ilmo_redis
    volumes:
      - ilmo-redis:/data

networks:
  default:
    external:
      name: prodeko-docker-net

volumes:
  ilmo-redis:
