services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - cache-volume:/data
    restart: unless-stopped

  db:
    image: debezium/postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
      - ./docker/postgres/db_setup.dev.sh:/docker-entrypoint-initdb.d/db_setup.dev.sh
    ports:
      - "6543:5432"
    restart: unless-stopped
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

volumes:
  db-volume:
  cache-volume:
