version: "3.8"
services:
  server:
    image: ilmo-server
    entrypoint: yarn server start
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

  worker:
    image: ilmo-worker
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
      - server

  redis:
    image: redis:6-alpine
    volumes:
      - cache-prod-volume:/data

  db:
    image: postgres:11
    env_file:
      - .env.production
    working_dir: /
    volumes:
      - db-prod-volume:/var/lib/postgresql/data
      - ./docker/scripts/production:/docker-entrypoint-initdb.d/
      - ./data:/data
    restart: unless-stopped
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

# networks:
#   default:
#     external:
#       name: prodeko-docker-net

volumes:
  db-prod-volume:
  cache-prod-volume:
