# Docker-compose file to debug production build issues.
# Build the image first:
#
# $ docker build --build-arg ROOT_URL="http://localhost:5678" --tag ilmo-server .
# $ docker tag ilmo-server ilmo-worker
#
# Then run this compose stack with 'docker compose -f docker-compose.test.prod.yml up'
#
# To run migrations on first start, override the server command to:
# pnpm --filter @app/db run migrate

version: "3.8"
services:
  server:
    image: ilmo-server
    container_name: ilmo_server
    command: ["pnpm", "--filter", "@app/server", "run", "start"]
    ports:
      - "5678:5678"
    env_file:
      - .env.production
    depends_on:
      - redis
      - db

  worker:
    image: ilmo-worker
    container_name: ilmo_worker
    command: ["pnpm", "--filter", "@app/worker", "run", "start"]
    env_file:
      - .env.production
    depends_on:
      - redis
      - server

  redis:
    image: redis:6-alpine
    container_name: ilmo_redis
    volumes:
      - ilmo-redis:/data

  db:
    image: debezium/postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env.production
    working_dir: /
    volumes:
      - ilmo-postgres:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d/
      - ./data:/data
    restart: unless-stopped
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c
      log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

volumes:
  ilmo-redis:
  ilmo-postgres:
